######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 30 20:36:46 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += filegenerator.h filegenh.h thread.h
FORMS += hw5gui.ui
SOURCES += filegen.cpp filegenerator.cpp thread.cpp
